SHOW DATABASES;
USE queries_mysql;
SHOW TABLES;
DESCRIBE EMPLEADOS;
DESCRIBE DEPARTAMENTOS;
SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;
SELECT empno,deptno,ename,job,mgr,hiredate,sal,comm FROM EMPLEADOS WHERE comm=0;
SELECT empno,deptno,ename,job,mgr,hiredate,sal,comm FROM queries_mysql.EMPLEADOS WHERE comm >=500;
SELECT empno,deptno,ename,job,mgr,hiredate,sal,comm FROM queries_mysql.EMPLEADOS WHERE comm !=0;
SELECT empno,deptno,ename,job,mgr,hiredate,sal FROM EMPLEADOS WHERE sal >=500 ORDER BY sal asc;
SELECT DISTINCT  JOB FROM EMPLEADOS;
SELECT DISTINCT SAL FROM EMPLEADOS;
SELECT EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM FROM EMPLEADOS WHERE DEPTNO=30;
SELECT EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM FROM EMPLEADOS WHERE DEPTNO=30 AND JOB='SALESMAN';
SELECT EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM FROM EMPLEADOS WHERE JOB='SALESMAN' AND SAL >=1000;
SELECT EMPNO,DEPTNO,ENAME FROM EMPLEADOS WHERE DEPTNO=30 LIMIT 1;
SELECT EMPNO,DEPTNO,ENAME FROM EMPLEADOS WHERE DEPTNO=30 LIMIT 5;
SELECT count(SAL) FROM EMPLEADOS;
SELECT count(*) FROM EMPLEADOS;
SELECT max(SAL) FROM EMPLEADOS;
SELECT min(SAL) FROM EMPLEADOS;
SELECT AVG(SAL) FROM EMPLEADOS;
SELECT AVG(SAL) FROM EMPLEADOS WHERE DEPTNO=20;
SELECT round(AVG(SAL),2) FROM EMPLEADOS;
SELECT round(AVG(SAL),2) FROM EMPLEADOS WHERE JOB LIKE 'SALE%';
SELECT concat("El empleado ",ENAME, " es del departamento ",DEPTNO ) AS usuario_departamento FROM EMPLEADOS;

SELECT sum(SAL) AS suma_salario FROM EMPLEADOS ;
SELECT length(ENAME) FROM EMPLEADOS;
INSERT INTO EMPLEADOS (EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM) VALUES
(8035,30,'PETER', 'SALESMAN','7698','2021-07-12 00:00:00',1150,600);
UPDATE EMPLEADOS SET ENAME='PEDRO' WHERE EMPNO='8035';
SELECT EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM FROM EMPLEADOS where ENAME='PEDRO' ;
SELECT EMPNO,DEPTNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM FROM EMPLEADOS where SAL>=1000 AND DEPTNO=30;
DELETE FROM EMPLEADOS WHERE ENAME='PEDRO' AND EMPNO='8035';
SELECT EMPLEADOS.EMPNO AS empleado_numero, EMPLEADOS.ENAME AS email_name FROM EMPLEADOS ORDER BY EMPNO DESC;
SELECT EMPNO,ENAME, JOB,MGR,SAL,DNAME,LOC FROM EMPLEADOS RIGHT JOIN DEPARTAMENTOS ON EMPLEADOS.DEPTNO=DEPARTAMENTOS.DEPTNO;
SELECT E.EMPNO,E.ENAME,D.DNAME,D.LOC FROM EMPLEADOS E LEFT JOIN DEPARTAMENTOS D ON E.DEPTNO=D.DEPTNO;
SELECT ENAME,JOB FROM EMPLEADOS UNION ALL SELECT DNAME,LOC FROM DEPARTAMENTOS;
SELECT ENAME,JOB FROM EMPLEADOS UNION SELECT DNAME,LOC FROM DEPARTAMENTOS;
SELECT SAL, COUNT(SAL) AS CANTOTALSAL FROM EMPLEADOS GROUP BY SAL;
SELECT SAL, COUNT(SAL) AS CANTOTALSAL FROM EMPLEADOS GROUP BY SAL HAVING CANTOTALSAL>1;
SELECT ENAME,JOB,MGR,SAL FROM EMPLEADOS WHERE ENAME IN('PETER','PEDRO');
SELECT ENAME,JOB,MGR,SAL FROM EMPLEADOS WHERE ENAME NOT IN('PETER','PEDRO');
SELECT ENAME, JOB, MGR ,SAL,COMM FROM EMPLEADOS WHERE JOB LIKE '%MAN%';
SELECT ENAME, JOB, MGR ,SAL,COMM FROM EMPLEADOS WHERE JOB LIKE 'MAN%';
SELECT ENAME, JOB, MGR ,SAL,COMM FROM EMPLEADOS WHERE COMM IS NULL;
SELECT ENAME, JOB, MGR ,SAL,COMM FROM EMPLEADOS WHERE COMM IS NOT NULL;
SELECT EMPNO,DEPTNO,JOB,MGR,SAL,COMM FROM EMPLEADOS WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-04-01';
SELECT E.EMPNO,E.ENAME,D.DNAME,D.LOC FROM EMPLEADOS E LEFT JOIN DEPARTAMENTOS D ON E.DEPTNO=D.DEPTNO WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-04-01';
SELECT ENAME, JOB, MGR ,SAL,COMM FROM EMPLEADOS WHERE DEPTNO=(SELECT DEPTNO FROM DEPARTAMENTOS WHERE LOC='NEW YORK');
RENAME TABLE EMPLEADOS2 TO EMPLEADOS;



